from typing import Dict, Any, Optional, List
from datetime import datetime
import json
import random
import uuid

from anthropic import Anthropic
from loguru import logger
from sqlalchemy.orm import Session

from app.config import settings
from app.schemas.ai import ClaudeReviewResponse


class ClaudeReviewService:
    """Service for reviewing workout plans using Claude 3.5 Sonnet"""
    
    def __init__(self, db: Optional[Session] = None):
        self.db = db
        self.mock_mode = settings.mock_llm
        if not self.mock_mode and settings.anthropic_api_key:
            self.client = Anthropic(api_key=settings.anthropic_api_key)
        else:
            self.client = None
    
    def review_plan(
        self,
        plan: Dict[str, Any],
        validator_results: Optional[Dict[str, Any]] = None,
        user_id: Optional[int] = None,
        week_number: Optional[int] = None,
    ) -> ClaudeReviewResponse:
        """
        Review a workout plan using Claude 3.5 Sonnet.
        
        Args:
            plan: The workout plan generated by GPT-4
            validator_results: Results from the deterministic validator (if available)
            user_id: User ID for logging
            week_number: Week number for logging context
            
        Returns:
            ClaudeReviewResponse with review results
        """
        request_id = str(uuid.uuid4())
        
        log_ctx = {
            "claude_review_id": request_id,
            "model": settings.anthropic_model,
            "user_id": user_id,
            "week_number": week_number,
            "plan_keys": list(plan.keys()) if isinstance(plan, dict) else None,
        }
        
        logger.bind(**log_ctx).info("[CLAUDE_REVIEW] Starting plan review")
        
        if self.mock_mode:
            logger.info("[CLAUDE_REVIEW] Using MOCK mode for plan review")
            return self._generate_mock_review(plan, validator_results, request_id)
        
        if not self.client:
            logger.warning("[CLAUDE_REVIEW] Claude client not initialized, returning approved without review")
            return ClaudeReviewResponse(
                approved=True,
                improved_plan=None,
                review_notes="Claude review not available (API key not configured)",
                changelog=None,
                model=settings.anthropic_model,
                usage=None,
            )
        
        try:
            # Build review prompt
            prompt = self._build_review_prompt(plan, validator_results)
            
            log_ctx["prompt_length"] = len(prompt)
            logger.bind(**log_ctx).debug("[CLAUDE_REVIEW] Review prompt built")
            
            # Call Claude API
            message = self.client.messages.create(
                model=settings.anthropic_model,
                max_tokens=16000,  # Increased to handle large JSON responses
                temperature=0.3,  # Lower temperature for more consistent reviews
                messages=[
                    {
                        "role": "user",
                        "content": prompt
                    }
                ]
            )
            
            # Parse response
            response_text = message.content[0].text if message.content else ""
            usage_info = {
                "input_tokens": message.usage.input_tokens,
                "output_tokens": message.usage.output_tokens,
            } if message.usage else None
            
            log_ctx.update({
                "response_length": len(response_text),
                "usage": usage_info,
            })
            logger.bind(**log_ctx).info("[CLAUDE_REVIEW] Claude API call successful")
            
            # Parse Claude's response
            review_result = self._parse_review_response(response_text, plan)
            
            # Log to database if available
            if self.db and user_id:
                self._log_claude_review(
                    user_id=user_id,
                    request_id=request_id,
                    plan=plan,
                    validator_results=validator_results,
                    response_text=response_text,
                    review_result=review_result,
                    usage=usage_info,
                )
            
            return ClaudeReviewResponse(
                approved=review_result.get("approved", True),
                improved_plan=review_result.get("improved_plan"),
                review_notes=review_result.get("review_notes", ""),
                changelog=review_result.get("changelog"),
                model=settings.anthropic_model,
                usage=usage_info,
            )
            
        except Exception as e:
            error_context = {**log_ctx, "error": str(e)}
            logger.bind(**error_context).exception("[CLAUDE_REVIEW] Claude API call failed")
            
            # Log error to database if available
            if self.db and user_id:
                try:
                    from app.services.ai_service import AIService
                    ai_service = AIService(self.db)
                    
                    prompt_summary = f"Review plan with {len(plan.get('workouts', []))} workouts"
                    
                    ai_service._log_ai_response(
                        request_type="claude_plan_review",
                        user_id=user_id,
                        prompt=prompt_summary,
                        request_payload={
                            "plan_keys": list(plan.keys()),
                            "has_validator_results": validator_results is not None,
                        },
                        response_text="",
                        model=settings.anthropic_model,
                        parse_success=False,
                        error_message=str(e),
                    )
                except Exception as log_error:
                    logger.warning(f"[CLAUDE_REVIEW] Failed to log error to database: {log_error}")
            
            # Fallback: approve plan if Claude fails
            return ClaudeReviewResponse(
                approved=True,
                improved_plan=None,
                review_notes=f"Claude review failed: {str(e)}. Plan approved by default.",
                changelog=None,
                model=settings.anthropic_model,
                usage=None,
            )
    
    def _build_review_prompt(
        self,
        plan: Dict[str, Any],
        validator_results: Optional[Dict[str, Any]] = None,
    ) -> str:
        """Build the prompt for Claude to review the plan"""
        
        plan_json = json.dumps(plan, indent=2, default=str)
        
        prompt = f"""You are an expert sports coach reviewing a training plan generated by another AI system.

Your task is to:
1. Verify the plan's progression, safety, and coherence
2. Identify any potential improvements
3. If improvements are needed, provide an improved version of the plan

TRAINING PLAN TO REVIEW:
{plan_json}
"""
        
        if validator_results:
            validator_json = json.dumps(validator_results, indent=2, default=str)
            prompt += f"""

VALIDATOR RESULTS:
{validator_json}
"""
        
        prompt += """
REVIEW CRITERIA:
1. **Progression**: Check if weekly volume/intensity increases are appropriate (max 10-15% per week for beginners, 7-10% for intermediate, 5-7% for advanced)
2. **Safety**: Ensure adequate rest days (minimum 1 per week), no excessive high-intensity sessions, proper recovery between hard sessions
3. **Coherence**: Verify that workouts align with the stated goals, level, and sport type
4. **Structure**: Check that workouts have proper warmup, main, and cooldown segments
5. **Periodization**: Ensure appropriate phase distribution (base, build, peak, taper) based on weeks remaining

RESPONSE FORMAT (JSON):
{
    "approved": true/false,
    "review_notes": "Detailed explanation of your review findings",
    "changelog": ["Change 1", "Change 2", ...] or null if approved,
    "improved_plan": { ... improved plan JSON ... } or null if approved
}

If the plan is good, set "approved": true and leave "improved_plan" as null.
If improvements are needed, set "approved": false, provide "improved_plan" with the corrected version, and list changes in "changelog".

IMPORTANT: The improved_plan must maintain the same structure as the original plan, including all required fields.
"""
        
        return prompt
    
    def _parse_review_response(
        self,
        response_text: str,
        original_plan: Dict[str, Any],
    ) -> Dict[str, Any]:
        """Parse Claude's response and extract review results"""
        
        try:
            # Try to extract JSON from response (might be wrapped in markdown)
            response_text = response_text.strip()
            if response_text.startswith("```json"):
                response_text = response_text[7:]  # Remove ```json
            if response_text.startswith("```"):
                response_text = response_text[3:]  # Remove ```
            if response_text.endswith("```"):
                response_text = response_text[:-3]  # Remove trailing ```
            response_text = response_text.strip()
            
            review_data = json.loads(response_text)
            
            # Validate structure
            if not isinstance(review_data, dict):
                raise ValueError("Review response is not a dictionary")
            
            return {
                "approved": review_data.get("approved", True),
                "review_notes": review_data.get("review_notes", ""),
                "changelog": review_data.get("changelog"),
                "improved_plan": review_data.get("improved_plan"),
            }
            
        except json.JSONDecodeError as e:
            logger.warning(f"[CLAUDE_REVIEW] Failed to parse JSON response: {e}")
            logger.debug(f"[CLAUDE_REVIEW] Response text: {response_text[:1000]}")
            
            # Try to extract partial JSON if available
            try:
                # Try to find JSON in the response even if truncated
                json_start = response_text.find('{')
                json_end = response_text.rfind('}')
                if json_start >= 0 and json_end > json_start:
                    partial_json = response_text[json_start:json_end+1]
                    # Try to fix common truncation issues
                    if not partial_json.strip().endswith('}'):
                        # Add closing braces for truncated JSON
                        open_braces = partial_json.count('{') - partial_json.count('}')
                        if open_braces > 0:
                            partial_json += '}' * open_braces
                            # Try to close any open strings
                            if partial_json.count('"') % 2 != 0:
                                partial_json = partial_json.rstrip('"') + '"}'
                    
                    try:
                        review_data = json.loads(partial_json)
                        logger.info("[CLAUDE_REVIEW] Successfully parsed partial/truncated JSON")
                        return {
                            "approved": review_data.get("approved", False),  # Default to False if we can't parse properly
                            "review_notes": review_data.get("review_notes", f"Partial response parsed. Original error: {str(e)}"),
                            "changelog": review_data.get("changelog"),
                            "improved_plan": review_data.get("improved_plan"),
                        }
                    except json.JSONDecodeError:
                        pass  # Fall through to default behavior
            except Exception as parse_error:
                logger.debug(f"[CLAUDE_REVIEW] Failed to extract partial JSON: {parse_error}")
            
            # Fallback: if we can't parse at all, reject the plan to be safe
            # (better to fail safe than approve a potentially invalid plan)
            return {
                "approved": False,
                "review_notes": f"Could not parse Claude's response due to: {str(e)}. Response may be truncated. Plan needs manual review.",
                "changelog": ["JSON parsing failed - response may be truncated"],
                "improved_plan": None,
            }
    
    def _generate_mock_review(
        self,
        plan: Dict[str, Any],
        validator_results: Optional[Dict[str, Any]],
        request_id: str,
    ) -> ClaudeReviewResponse:
        """Generate a mock review response for testing"""
        
        logger.info("[CLAUDE_REVIEW][MOCK] Generating mock review")
        
        # In mock mode, randomly approve or suggest improvements
        approved = random.random() > 0.3  # 70% approval rate
        
        if approved:
            return ClaudeReviewResponse(
                approved=True,
                improved_plan=None,
                review_notes="Mock review: Plan looks good. Progression is appropriate, safety guidelines are followed, and structure is coherent.",
                changelog=None,
                model=settings.anthropic_model,
                usage={"input_tokens": 1000, "output_tokens": 200},
            )
        else:
            # Generate a mock improved plan (just copy the original with minor changes)
            improved_plan = plan.copy()
            if "workouts" in improved_plan and isinstance(improved_plan["workouts"], list):
                # Add a note to indicate it was improved
                improved_plan["_claude_improved"] = True
            
            return ClaudeReviewResponse(
                approved=False,
                improved_plan=improved_plan,
                review_notes="Mock review: Plan needs minor adjustments. Suggested improvements: added recovery day, adjusted intensity progression.",
                changelog=[
                    "Added additional recovery day",
                    "Adjusted intensity progression for week 2",
                    "Improved workout structure consistency",
                ],
                model=settings.anthropic_model,
                usage={"input_tokens": 1000, "output_tokens": 500},
            )
    
    def _log_claude_review(
        self,
        user_id: int,
        request_id: str,
        plan: Dict[str, Any],
        validator_results: Optional[Dict[str, Any]],
        response_text: str,
        review_result: Dict[str, Any],
        usage: Optional[Dict[str, Any]],
    ) -> None:
        """Log Claude review to database (if AI logging table exists)"""
        
        try:
            # Try to use the same logging mechanism as AIService
            from app.services.ai_service import AIService
            ai_service = AIService(self.db)
            
            # Build prompt summary
            prompt_summary = f"Review plan with {len(plan.get('workouts', []))} workouts"
            
            ai_service._log_ai_response(
                request_type="claude_plan_review",
                user_id=user_id,
                prompt=prompt_summary,
                request_payload={
                    "plan_keys": list(plan.keys()),
                    "has_validator_results": validator_results is not None,
                },
                response_text=response_text,
                model=settings.anthropic_model,
                parse_success=review_result.get("approved") is not None,
                error_message=None,
            )
            
        except Exception as e:
            logger.warning(f"[CLAUDE_REVIEW] Failed to log review to database: {e}")
    
    def should_review_plan(
        self,
        validator_has_errors: bool = False,
        validator_has_warnings: bool = False,
    ) -> bool:
        """
        Determine if a plan should be reviewed by Claude.
        
        Args:
            validator_has_errors: Whether the validator found errors
            validator_has_warnings: Whether the validator found warnings
            
        Returns:
            True if the plan should be reviewed
        """
        if not settings.enable_claude_review:
            return False
        
        # Always review if validator found errors
        if validator_has_errors:
            return True
        
        # Review based on percentage if validator found warnings
        if validator_has_warnings:
            return random.random() < (settings.claude_review_percentage / 100.0)
        
        # Review based on configured percentage
        return random.random() < (settings.claude_review_percentage / 100.0)

