from pydantic import BaseModel, Field, conlist
from typing import List, Optional, Dict, Any, Literal
from datetime import date, datetime
from app.schemas.workout import WorkoutStatus

class CoachMemoryItem(BaseModel):
    """A specific fact or piece of feedback remembered by the Agent."""
    key: str = Field(..., description="Unique key for the memory (e.g., 'knee_pain_left')")
    value: str = Field(..., description="The content of the memory")
    category: Literal["physiological", "psychological", "preference", "injury"]
    confidence: float = Field(default=1.0, ge=0.0, le=1.0)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    expires_at: Optional[datetime] = None

class RecentWorkoutContext(BaseModel):
    """Rich context about a past workout for RAG injection."""
    workout_id: int
    date: date
    type: str
    sport: str
    planned_duration: int
    actual_duration: Optional[int]
    planned_intensity: Optional[str]
    rpe: Optional[int]
    tss: Optional[float]
    success_rating: Optional[int] = Field(None, description="1-5 rating of adherence/success")
    notes: Optional[str]
    # Key Metrics needed for decision making
    failure_point: Optional[str] = Field(None, description="Why did the athlete fail? (e.g. 'muscular_failure', 'cardio_limit')")
    peak_metric: Optional[str] = Field(None, description="e.g. 'Max Power 300W'")

class AthleteStateAssessment(BaseModel):
    """The Agent's reasoning about the athlete's current state."""
    current_phase: str = Field(..., description="Base, Build, Peak, Taper, Recovery")
    fatigue_level: Literal["low", "moderate", "high", "extreme"]
    injury_risk: Literal["low", "moderate", "high"]
    mental_freshness: int = Field(..., ge=1, le=10)
    
    # Quantitative Metrics
    ctl: float = Field(..., description="Chronic Training Load (Fitness)")
    atl: float = Field(..., description="Acute Training Load (Fatigue)")
    tsb: float = Field(..., description="Training Stress Balance (Form)")
    
    # Qualitative Reasoning
    reasoning: str = Field(..., description="Chain of thought explaining the assessment")
    focus_for_week: str = Field(..., description="Main objective (e.g., 'Recover leg strength', 'Boost VO2Max')")
    recommended_modifications: List[str] = Field(default_factory=list, description="Specific changes to standard plan")

class UnifiedPlanRequest(BaseModel):
    """Input for generating a plan using the Agentic Coach."""
    user_id: int
    target_week_start: date
    goal: str
    available_days: List[str]
    equipment: List[str]
    
    # Context (Injected by Service, not API user)
    recent_workouts: List[RecentWorkoutContext]
    coach_memories: List[CoachMemoryItem]
    athlete_assessment: Optional[AthleteStateAssessment] = None

class GeneratedWorkout(BaseModel):
    """A single workout generated by the Agent."""
    day: str
    date: date
    sport: str
    type: str # 'endurance', 'strength', 'recovery', 'rest'
    duration_minutes: int
    structure_json: Dict[str, Any] # Complete JSON structure (warmup, main, cooldown)
    rpe_target: int
    focus_metric: str # 'heart_rate', 'pace', 'power', 'weight'
    reasoning: str = Field(..., description="Why this specific workout? (e.g. 'Matched with Tuesday's failure')")

class AgenticWeeklyPlan(BaseModel):
    """The final output of the Agentic Coach."""
    week_number: int
    phase: str
    focus: str
    workouts: List[GeneratedWorkout]
    weekly_summary_reasoning: str = Field(..., description="Explanation of the week's logic")
